# language: en
# spec-id: PT-002
# traceability:
#   flowcharts: _reversa_sdd/flowcharts/spec.md (change-request FSM)
#   target_architecture: BC-01 spec (AGG-ChangeRequest)
#   business_rules: R-SP-4, R-SP-8 (+ D-4 real /speckit.tasks generator)
#   paradigma_alvo: OO-with-DI — behavioral parity
Feature: Change request lifecycle and archival blocker
  As a reviewer
  I want change requests to block archival and drive spec status
  So that the migrated plugin preserves the review-flow semantics

  @paridade @critico
  Scenario: Filing a change request reopens a spec in review
    Given a spec in status "review"
    When a change request is filed
    Then the change request is "open" with archivalBlocker true
    And the spec transitions to "reopened"

  @paridade @critico
  Scenario: Addressing all tasks clears the blocker
    Given an open change request with attached tasks generated by /speckit.tasks
    When all attached tasks are marked done
    Then the change request becomes "addressed"
    And the archival blocker clears

  @paridade
  Scenario: Duplicate change requests are rejected by normalized title
    Given a non-addressed change request titled "Fix login   bug"
    When a new change request titled "fix login bug" is filed
    Then the new change request is rejected as a duplicate
